add navigation setting
k-road-dang/k_road_dang_frontend pull request #2
Opened 2022-06-23 07:42 UTC by hhyemi

add navigation setting ⚙️

2022-06-23 10:27 UTC, SangWonyy requested changes

2022-06-23 10:27 UTC, SangWonyy commented on src/navigation/CommunityNavigator.tsx
> +  Community: undefined;
1. type은 type 파일에다가 별도로 관리하는게 좋지않을까라는 생각
2. paramList, prop에 대한 타입 정의를 각 네비게이터 별로 분리하는 것도 좋긴한데, 하나로 통합해서 관리하면 오히려 더 편하고 좋을 듯합니다. 모든 네비게이터 관련 paramList, props 관리를 한 곳에서 하면 찾아가기도 편하고 선언하기도 편하고 개인적인생각.
3.

2022-06-23 10:27 UTC, SangWonyy commented on src/navigation/CommunityNavigator.tsx
> +      <CommunityStack.Screen name="Community" component={CommunityScreen} />
1. name="Community" 이 부분을 enum으로 관리하면 실수 유발을 감소.
1-1 navigator.navigation("") 이렇게 사용하면서 들어가야 되는 name이름이 까먹을 확률도 높고 오타 낼 확률이 높아서 enum으로 관리하면 실수할 가능성이 확 줄어든다고 생각.
1-2 또한 네임 변경 시 enum의 벨류 값만 변경해주면 한번에 다 반영이 되기 때문에 유지보수 측면에서도 좋다고 생각.

2022-06-23 10:27 UTC, SangWonyy commented on src/providers/navigation.tsx
> +  return <NavigationContainer>{children}</NavigationContainer>;
여기에 대한 용도가 무엇일까.  의미상 그냥 넣은건가유

2022-06-23 10:27 UTC, SangWonyy commented on src/screens/register/birth.tsx
> +type BirthNavigationProps = StackNavigationProp<RegisterStackParamList, "Birth">;
CommunityNavigator.tsx 에서 리뷰한 것처럼 스크린 마다 다 분리해서 선언하기 보다는 하나로 관리하고 type 파일에서 불러오면 더 관리가 편한 것으로 예상!

2022-06-23 10:27 UTC, SangWonyy commented on src/screens/register/birth.tsx
> +  navigation: BirthNavigationProps;
interface랑 type이랑 큰 차이가 없다면 둘 중에 하나로 통합해서 사용하는게 좋다고 생각!

2022-06-28 06:37 UTC, hhyemi commented on src/providers/navigation.tsx
> +  return <NavigationContainer>{children}</NavigationContainer>;
추후에 Navigation에 추가할 내용이 있으면 App쪽이 지저분해질까봐 따로 만들었어요
App을 깔끔하게 보이기 위해서였는데 나중에 나눌필요가 없어보이면 합쳐도 괜찮을거같아요

2022-06-28 06:38 UTC, hhyemi commented on src/navigation/CommunityNavigator.tsx
> +  Community: undefined;
👍

2022-06-28 06:38 UTC, hhyemi commented on src/navigation/CommunityNavigator.tsx
> +      <CommunityStack.Screen name="Community" component={CommunityScreen} />
👍

2022-06-28 06:38 UTC, hhyemi commented on src/screens/register/birth.tsx
> +type BirthNavigationProps = StackNavigationProp<RegisterStackParamList, "Birth">;
👍

2022-06-28 06:38 UTC, hhyemi commented on src/screens/register/birth.tsx
> +  navigation: BirthNavigationProps;
👍

2022-06-28 06:40 UTC, merged